export const AUCTION_LIST_SET = "AUCTION_LIST_SET";
export const CURRENT_AUCTION_SET = "CURRENT_AUCTION_SET";
export const BID_AMOUNT_SET = "BID_AMOUNT_SET";
export const BIDDING_LIST_SET = "BIDDING_LIST_SET";
export const SET_SELECTED_AUCTIONED_ASSET = "SET_SELECTED_AUCTIONED_ASSET";
export const SET_AUCTION_PAGE_NUMBER = "SET_AUCTION_PAGE_NUMBER";
export const SET_AUCTION_PAGE_SIZE = "SET_AUCTION_PAGE_SIZE";
