export const MARKET_LIST_SET = "MARKET_LIST_SET";
export const SET_COINGEKO_PRICE = "SET_COINGEKO_PRICE";
export const SET_CSWAP_API_PRICE = "SET_CSWAP_API_PRICE";
export const LP_PRICES_SET = "LP_PRICES_SET";
