export const chainNetworks = {
    agoric: {
        chainId: "agoric-3",
        chainName: "Agoric",
        rpc: "https://airdrop.zenscape.one/agoric-rpc",
        rest: "https://airdrop.zenscape.one/agoric-api",
        explorerUrlToTx: "https://bigdipper.live/agoric/transactions/{txHash}",
        coinDenom: "BLD",
        coinMinimalDenom: "ubld",
        coinDecimals: 6,
        prefix: "agoric",
        coinType: 564,
    },
    injective: {
        chainId: "injective-1",
        chainName: "Injective v1.1",
        rpc: "https://airdrop.zenscape.one/injective-rpc",
        rest: "https://airdrop.zenscape.one/injective-api",
        explorerUrlToTx: "https://explorer.injective.network/transaction/{txHash}",
        coinDenom: "INJ",
        coinMinimalDenom: "inj",
        coinDecimals: 18,
        prefix: "inj",
        coinType: 60,
    },
    luna2: {
        chainId: "phoenix-1",
        chainName: "Terra 2.0",
        rpc: "https://airdrop.zenscape.one/luna-rpc",
        rest: "https://airdrop.zenscape.one/luna-api",
        explorerUrlToTx: "https://finder.terra.money/mainnet/tx/{txHash}",
        coinDenom: "LUNA",
        coinMinimalDenom: "uluna",
        coinDecimals: 6,
        prefix: "terra",
        coinType: 330,
        coinGeckoId: "terra-luna-2"
    },
    cronos: {
        chainId: "crypto-org-chain-mainnet-1",
        chainName: "Cronos",
        rpc: "https://rpc.cosmos.directory/cryptoorgchain",
        rest: "https://rest.cosmos.directory/cryptoorgchain",
        explorerUrlToTx: "https://www.mintscan.io/crypto-org/txs/{txHash}",
        coinDenom: "CRO",
        coinMinimalDenom: "basecro",
        coinDecimals: 8,
        prefix: "cro",
        coinType: 394,
    },
    evmos: {
        chainId: "evmos_9001-2",
        chainName: "Evmos",
        rpc: "https://airdrop.zenscape.one/evmos-rpc",
        rest: "https://airdrop.zenscape.one/evmos-api",
        explorerUrlToTx: "https://www.mintscan.io/evmos/txs/{txHash}",
        coinDenom: "EVMOS",
        coinMinimalDenom: "aevmos",
        coinDecimals: 18,
        prefix: "evmos",
        coinType: 60,
    },
    secret: {
        chainId: "secret-4",
        chainName: "Secret Network",
        rpc: "https://rpc.scrt.network",
        rest: "https://api.scrt.network",
        explorerUrlToTx: "https://www.mintscan.io/secret/txs/{txHash}",
        coinDenom: "SCRT",
        coinMinimalDenom: "uscrt",
        coinDecimals: 6,
        prefix: "secret",
        coinType: 529,
    },
    persistence: {
        chainId: "core-1",
        chainName: "Persistence",
        rpc: "https://persistence-rpc.polkachu.com",
        rest: "https://persistence-api.polkachu.com",
        explorerUrlToTx: "https://www.mintscan.io/persistence/txs/{txHash}",
        coinDenom: "XPRT",
        coinMinimalDenom: "uxprt",
        coinDecimals: 6,
        prefix: "persistence",
        coinType: 750,
    },
};
